// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe2Up9HO0ym1Ze9O6DzRGf4YD8Nt70-rI',
    appId: '1:77862356548:web:e5dbc4ed908a8260481e11',
    messagingSenderId: '77862356548',
    projectId: 'cce-stu',
    authDomain: 'cce-stu.firebaseapp.com',
    storageBucket: 'cce-stu.appspot.com',
    measurementId: 'G-RR0TRD4EVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPyLQLjRoZG55gKnQ6FxtlzT2LJKMnJs',
    appId: '1:77862356548:android:02d3db580f5d036b481e11',
    messagingSenderId: '77862356548',
    projectId: 'cce-stu',
    storageBucket: 'cce-stu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJkjmaBzP3oVutoGTXN_Gg9wc-KowjfU',
    appId: '1:77862356548:ios:04787f152d5ef8e9481e11',
    messagingSenderId: '77862356548',
    projectId: 'cce-stu',
    storageBucket: 'cce-stu.appspot.com',
    iosBundleId: 'com.example.cceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJkjmaBzP3oVutoGTXN_Gg9wc-KowjfU',
    appId: '1:77862356548:ios:04787f152d5ef8e9481e11',
    messagingSenderId: '77862356548',
    projectId: 'cce-stu',
    storageBucket: 'cce-stu.appspot.com',
    iosBundleId: 'com.example.cceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe2Up9HO0ym1Ze9O6DzRGf4YD8Nt70-rI',
    appId: '1:77862356548:web:48699b80762ac028481e11',
    messagingSenderId: '77862356548',
    projectId: 'cce-stu',
    authDomain: 'cce-stu.firebaseapp.com',
    storageBucket: 'cce-stu.appspot.com',
    measurementId: 'G-KE52M560NG',
  );
}
